# Generated by Django 3.1.5 on 2021-01-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupchatWrappedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('total_msgs', models.IntegerField()),
                ('total_reacts', models.IntegerField()),
                ('most_frequent_time', models.IntegerField()),
                ('most_frequent_time_msg_count', models.IntegerField()),
                ('most_total_reacts_member', models.CharField(max_length=64)),
                ('most_total_reacts', models.IntegerField()),
                ('longest_streak_start', models.PositiveBigIntegerField()),
                ('longest_streak_end', models.PositiveBigIntegerField()),
                ('first_msg', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('word', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groupchatwrappedresult')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('score', models.FloatField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groupchatwrappedresult')),
            ],
        ),
        migrations.CreateModel(
            name='ReactCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('icon', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groupchatwrappedresult')),
            ],
        ),
    ]
