# Generated by Django 3.1.5 on 2021-01-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatwrappedresult',
            name='longest_streak_end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupchatwrappedresult',
            name='longest_streak_start',
            field=models.DateField(auto_now=True),
        ),
    ]
