# Generated by Django 3.1.5 on 2021-01-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210131_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatwrappedresult',
            name='longest_streak_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='groupchatwrappedresult',
            name='longest_streak_start',
            field=models.DateField(),
        ),
    ]
