# Generated by Django 3.1.5 on 2021-01-31 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_role_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatwrappedresult',
            name='chat_name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupchatwrappedresult',
            name='msg_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactcount',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchatwrappedresult',
            name='longest_streak_end',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='groupchatwrappedresult',
            name='longest_streak_start',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('word', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groupchatwrappedresult')),
            ],
        ),
    ]
