# Generated by Django 3.1.5 on 2021-01-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210131_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatwrappedresult',
            old_name='chat_name',
            new_name='title',
        ),
    ]
