# Generated by Django 3.1.5 on 2021-01-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210131_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatwrappedresult',
            old_name='msg_count',
            new_name='total_msgs',
        ),
        migrations.AddField(
            model_name='groupchatwrappedresult',
            name='total_reacts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
